[package]
name = "pong"
version = "0.1.0"
authors = ["coufal <coufalja@gmail.com>"]
edition = "2018"


[dependencies.rand]
version = "0.7"
[dependencies.amethyst]
version = "0.15"
[features]
default = ["vulkan"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]